device: cuda

data:
  N: 10000
  time_series_length: 100
  delta_t: 10
  planet: earth
  train_freq: 0.8
  train_file: ./data/earth_train.plk.gz
  valid_file: ./data/earth_val.plk.gz
  inference_file: ./data/earth_inf.plk.gz
train:
  n_epochs: 50
  batch_size: 128
  model:
    input_size: 1
    latent_size: 1
    output_size: 1
    encoder_num_units: [1024, 1024]
    decoder_num_units: [1024, 1024]
    weights_path: ./resources/earth/best_model.pth
inference:
  data:
    time_series_length: 100
    inference_file: ./data/earth_inf.plk.gz
  model:
    input_size: 1
    latent_size: 1
    output_size: 1
    encoder_num_units: [1024, 1024]
    decoder_num_units: [1024, 1024]
    weights_path: ./resources/earth/best_model.pth
  n_epochs: 100
  batch_size: 128